export const KINGDOMS = [
    {
        id: "lysanthia",
        name: "Lysanthia",
        kind: "kingdom",
        info: "Waldreich und alte Kulturen.",
        x: 0,
        y: 0,
        fill: "rgb(65,93,50)",
        stroke: "rgb(51,68,42)",
    },
    {
        id: "unclaimed",
        name: "Unclaimed",
        kind: "wildlands",
        info: "Umkämpftes Niemandsland.",
        x: 0,
        y: 0,
        fill: "rgb(226,213,182)",
        stroke: "rgb(165,156,134)",
    },
    {
        id: "graumark",
        name: "Graumark",
        kind: "kingdom",
        info: "Berge, Pässe und Festungen.",
        x: 0,
        y: 0,
        fill: "rgb(158,162,167)",
        stroke: "rgb(100,103,106)",
    },
    {
        id: "shalkaar",
        name: "Shalkaar",
        kind: "kingdom",
        info: "Unbekanntes Land umwoben von Mythen und Legenden.",
        x: 0,
        y: 0,
        fill: "rgb(66,66,66)",
        stroke: "rgb(27,27,27)",
    },
    {
        id: "valryndor",
        name: "Valryndor",
        kind: "kingdom",
        info: "Reiches Kernland mit vielen Städten.",
        x: 0,
        y: 0,
        fill: "rgb(137,193,199)",
        stroke: "rgb(87,122,126)",
    },
    {
        id: "tyrasalar",
        name: "Tyras Alar",
        kind: "kingdom",
        info: "Grenzland mit vielen alten Narben.",
        x: 0,
        y: 0,
        fill: "rgb(192,188,130)",
        stroke: "rgb(119,116,80)",
    },
    {
        id: "azmaran",
        name: "Azmaran",
        kind: "kingdom",
        info: "Händler und Piraten.",
        x: 0,
        y: 0,
        fill: "rgb(255,207,110)",
        stroke: "rgb(180,146,78)",
    },
    {
        id: "eldarion",
        name: "Eldarion",
        kind: "kingdom",
        info: "Hoher Norden voller Eis und Schnee.",
        x: 0,
        y: 0,
        fill: "rgb(214,211,211)",
        stroke: "rgb(133,133,133)",
    },
];
export const MARKERS = [
    {
        id: "city-aelvar",
        name: "Aelvar",
        kind: "city",
        layer: "cities",
        x: 338,
        y: 262,
        info: "Hauptstadt am Fluss.",
        ruler: "Fürstin Rhea",
    },
    {
        id: "city-karnhold",
        name: "Karnhold",
        kind: "city",
        layer: "cities",
        x: 468,
        y: 186,
        info: "Bergfestung und Erzstadt.",
        ruler: "Rat der Zehn",
    },
    {
        id: "place-shadowwood",
        name: "Schattenwald",
        kind: "place",
        layer: "places",
        x: 374,
        y: 336,
        info: "Dichter Wald mit alten Steinen.",
    },
    {
        id: "place-drachenpass",
        name: "Drachenpass",
        kind: "place",
        layer: "places",
        x: 452,
        y: 92,
        info: "Enger Pass zwischen Bergen.",
    },
    {
        id: "npc-maera",
        name: "Maera die Kartenmacherin",
        kind: "person",
        layer: "people",
        x: 327,
        y: 274,
        info: "Kennt geheime Wege und alte Grenzen.",
    },
    {
        id: "npc-thoren",
        name: "Thoren Eisenhand",
        kind: "person",
        layer: "people",
        x: 474,
        y: 193,
        info: "Wächter der Bergpässe.",
    },
];
export const LAYER_RULES = {
    kingdoms: 1,
    cities: 4,
    places: 6,
    people: 8,
};
export const KINGDOM_LABEL_POSITIONS = {
    lysanthia: {x: 170, y: 275},
    unclaimed: {x: 365, y: 405},
    graumark: {x: 565, y: 180},
    shalkaar: {x: 585, y: 470},
    valryndor: {x: 340, y: 404},
    tyrasalar: {x: 525, y: 315},
    azmaran: {x: 150, y: 486},
    eldarion: {x: 0, y: 0},
};